### ISSUE TITLE
Segmentation Error? —> '/usr/local/lib/libavformat.56.dylib' (no such file), '/usr/lib/libavformat.56.dylib' (no such file) — referenced from streaming_extractor_music

### ISSUE THREAD

**Issue by bkresnick** [adamjakab/BeetsPluginXtractor#32]
Hello! When I run the Xtractor it fails saying that it cannot find the json output. But it looks like the output is successful.

What should I do? Thanks for your consideration... and the plugin!!

Maybe my installing Essentia with homebrew (per the instructions) after installing beets with pip is behind the issue? I barely am familiar with the command line, programming, etc so not sure how to troubleshoot further.

### Problem

```sh
$ My-Air-2:~ usr$ beet -vv xtractor serpents
user configuration: /Users/usr/.config/beets/config.yaml
data directory: /Users/usr/.config/beets
plugin paths: 
fetchart: google: Disabling art source due to missing key
fetchart: lastfm: Disabling art source due to missing key
inline: adding item field catalognum_adj
inline: adding album field albumartist_adj
inline: adding album field initials
inline: adding album field longAA
inline: adding album field shortAA
inline: adding album field catalognum_adj
inline: adding album field andAA
inline: adding album field and_adj
Sending event: pluginload
library database: /Users/usr/.config/beets/library.db
library directory: /Users/usr/MusicTest
Sending event: library_opened
Parsed query: AndQuery([AnyFieldQuery('serpents', ('artist', 'title', 'comments', 'album', 'albumartist', 'genre'), SubstringQuery)])
Parsed sort: NullSort()
xtractor: Combined query: AndQuery([AndQuery([AnyFieldQuery('serpents', ('artist', 'title', 'comments', 'album', 'albumartist', 'genre'), SubstringQuery)]), OrQuery([MatchQuery('bpm', None, fast=True), MatchQuery('average_loudness', None, fast=False), MatchQuery('danceable', None, fast=False), MatchQuery('gender', None, fast=False), MatchQuery('genre_rosamerica', None, fast=False), MatchQuery('voice_instrumental', None, fast=False), MatchQuery('mood_acoustic', None, fast=False), MatchQuery('mood_aggressive', None, fast=False), MatchQuery('mood_electronic', None, fast=False), MatchQuery('mood_happy', None, fast=False), MatchQuery('mood_sad', None, fast=False), MatchQuery('mood_party', None, fast=False), MatchQuery('mood_relaxed', None, fast=False), MatchQuery('mood_mirex', None, fast=False)])])
xtractor: Number of items to be processed: 6
xtractor: Running analysis for: /Volumes/Data/Music2/Abschm2024_MMLPXX808/MMXX808_01.aiff
xtractor: Extractor: /Users/usr/.config/beets/plugin_Xtractor/streaming_extractor_music
xtractor: Input: /Volumes/Data/Music2/Abschm2024_MMLPXX808/MMXX808_01.aiff
xtractor: Output: /Users/usr/.config/beets/plugin_Xtractor/xtraction_data/30028909-A1.json
xtractor: Profile: /Users/usr/.config/beets/plugin_Xtractor/xtraction_data/profile.yml
xtractor: Executing: "/Users/usr/.config/beets/plugin_Xtractor/streaming_extractor_music" "/Volumes/Data/Music2/Abschm2024_MMLPXX808/MMXX808_01.aiff" "/Users/usr/.config/beets/plugin_Xtractor/xtraction_data/30028909-A1.json" "/Users/usr/.config/beets/plugin_Xtractor/xtraction_data/profile.yml"
xtractor: The process exited with code: -6
xtractor: Process stdout: 
xtractor: Process stderr: dyld[32553]: Library not loaded: '/usr/local/lib/libavformat.56.dylib'
  Referenced from: '/Users/usr/.config/beets/plugin_Xtractor/streaming_extractor_music'
  Reason: tried: '/usr/local/lib/libavformat.56.dylib' (no such file), '/usr/lib/libavformat.56.dylib' (no such file)


xtractor: File not found: Output file(/Users/usr/.config/beets/plugin_Xtractor/xtraction_data/30028909-A1.json) not found!
Sending event: write
Sending event: after_write
```

### Setup

* OS: macOS Monterey Version 12.7.4
* Python version: 3.10.4
* Beets version: 2.0.0
* Turning off other plugins made problem go away (yes/no): No

My configuration (output of `beet config`) is:

```yaml
ignore: FLAC Flac flac WAV Wav wav 96 KHz
asciify_paths:
    default: yes
replace:
    '[&+]': And
    '[()!#.?,~]': ''
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _

# --------------- Plugins ---------------

plugins: discogs the inline fetchart ftintitle edit export types play xtractor
export:
    json:
        formatting:
            ensure_ascii: no
            indent: 4
            separators: [',', ': ']
            sort_keys: yes
    csv:
        formatting:
            delimiter: ','
            dialect: excel
    default_format: json
    jsonlines:
        formatting:
            ensure_ascii: no
            separators: [',', ': ']
            sort_keys: yes
    xml:
        formatting: {}
t
play:
    command: /Applications/VLC.app/Contents/MacOS/VLC --no-playlist-autostart
    warning_threshold: 100
    raw: yes
    use_folders: no
    relative_to:
    bom: no
extrafiles:
    patterns:
        all: '*.*'
xtractor:
    auto: no
    dry-run: no
    write: yes
    threads: 1
    force: no
    quiet: no
    keep_output: yes
    keep_profiles: no
    output_path: /Users/bresnick/.config/beets/plugin_Xtractor/xtraction_data
    essentia_extractor: /Users/bresnick/.config/beets/plugin_Xtractor/streaming_extractor_music
    extractor_profile:
        highlevel:
            svm_models:
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_acoustic.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_electronic.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/danceability.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_party.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/voice_instrumental.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/gender.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_happy.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_sad.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_relaxed.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/mood_aggressive.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/timbre.history
            - /Users/bresnick/.config/beets/plugin_Xtractor/svm_models/tonal_atonal.history
            compute: 1
        outputFormat: json
        outputFrames: 0
        lowlevel:
            frameSize: 2048
            hopSize: 1024
        chromaprint:
            compute: 0
    low_level_targets:
        bpm:
            path: rhythm.bpm
            type: integer
            required: yes
        danceability:
            path: rhythm.danceability
            type: float
        beats_count:
            path: rhythm.beats_count
            type: integer
        average_loudness:
            path: lowlevel.average_loudness
            type: float
            required: yes
    high_level_targets:
        danceable:
            path: highlevel.danceability.all.danceable
            type: float
            required: yes
        gender:
            path: highlevel.gender.value
            type: string
            required: yes
        is_male:
            path: highlevel.gender.all.male
            type: float
        is_female:
            path: highlevel.gender.all.female
            type: float
        genre_rosamerica:
            path: highlevel.genre_rosamerica.value
            type: string
            required: yes
        voice_instrumental:
            path: highlevel.voice_instrumental.value
            type: string
            required: yes
        is_voice:
            path: highlevel.voice_instrumental.all.voice
            type: float
        is_instrumental:
            path: highlevel.voice_instrumental.all.instrumental
            type: float
        mood_acoustic:
            path: highlevel.mood_acoustic.all.acoustic
            type: float
            required: yes
        mood_aggressive:
            path: highlevel.mood_aggressive.all.aggressive
            type: float
            required: yes
        mood_electronic:
            path: highlevel.mood_electronic.all.electronic
            type: float
            required: yes
        mood_happy:
            path: highlevel.mood_happy.all.happy
            type: float
            required: yes
        mood_sad:
            path: highlevel.mood_sad.all.sad
            type: float
            required: yes
        mood_party:
            path: highlevel.mood_party.all.party
            type: float
            required: yes
        mood_relaxed:
            path: highlevel.mood_relaxed.all.relaxed
            type: float
            required: yes
        mood_mirex:
            path: highlevel.moods_mirex.value
            type: string
            required: yes
        mood_mirex_cluster_1:
            path: highlevel.moods_mirex.all.Cluster1
            type: float
        mood_mirex_cluster_2:
            path: highlevel.moods_mirex.all.Cluster2
            type: float
        mood_mirex_cluster_3:
            path: highlevel.moods_mirex.all.Cluster3
            type: float
        mood_mirex_cluster_4:
            path: highlevel.moods_mirex.all.Cluster4
            type: float
        mood_mirex_cluster_5:
            path: highlevel.moods_mirex.all.Cluster5
            type: float

import:
    write: yes
    copy: no
    languages: en
    autotag: yes
art_filename: ${catalognum_adj}_art
paths:
    default: Music/$and_adj${year}_$catalognum_adj/${catalognum_adj}_$track
    comp: Music/Compilations/$and_adj${year}_$catalognum_adj/${catalognum_adj}_$track

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue
fetchart:
    auto: yes
    minwidth: 0
    maxwidth: 0
    quality: 0
    max_filesize: 0
    enforce_ratio: no
    cautious: no
    cover_names:
    - cover
    - front
    - art
    - album
    - folder
    sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - cover_art_url
    store_source: no
    high_resolution: no
    deinterlace: no
    cover_format:
    google_key: REDACTED
    google_engine: 001442825323518660753:hrh5ch1gjzm
    fanarttv_key: REDACTED
    lastfm_key: REDACTED
pathfields: {}
```

My plugin version (output of `beet xtractor -v`) is:

```text
(xtractor: Xtractor(beets-xtractor) plugin for Beets: v0.4.2
```
